var express = require('express');
var router = express.Router();


const itemList = [
    
    {'id': 1, 'terms':'DevOps','description':"DevOps is a collaborative approach that blends cultural principles, practices, and tools to enhance an organization's capacity for rapid application and service delivery. By continuously improving products at a faster rate than traditional methods, DevOps enables organizations to meet customer needs more effectively, fostering competitiveness in the market.",'references':'What is DevOps? - DevOps Models Explained - Amazon Web Services (AWS). (n.d.). Amazon Web Services, Inc. Retrieved July 30, 2023, from https://aws.amazon.com/devops/what-is-devops/'},
    {'id': 2, 'terms':'“Wall of Confusion”','description':'The DevOps Wall of Confusion refers to the divide between development and operations teams in traditional organizations. The development team aims to introduce new features, while the operations team seeks to maintain a stable environment. The clash arises when changes are made by the development team, potentially destabilizing the environment, causing a conflict between pushing changes and maintaining stability. DevOps seeks to break down this wall by fostering collaboration and alignment between these teams to achieve faster and more reliable application delivery.','references':'Kaiser, A. K. (2021, January 13). DevOps Wall of Confusion Explained. Technopedia. http://technopedia.info/devops/devops-wall-of-confusion-explained/'},
    {'id': 3, 'terms':'Agile','description':'The Agile Methodology is an iterative project management and software development approach that emphasizes collaboration, customer feedback, and frequent releases. It enable development teams to adapt to changing market conditions and customer demands by continuously incorporating changes and delivering usable versions of products in smaller batches, providing the flexibility to address customer needs and expectations in real-time.','references':'Atlassian. (n.d.). Agile vs DevOps. Atlassian. Retrieved July 30, 2023, from https://www.atlassian.com/devops/what-is-devops/agile-vs-devops'},
    {'id': 4, 'terms':'Microservices','description':'Microservices are a software development approach where applications are built as small, independent services that communicate through well-defined APIs, managed by self-contained teams. This architecture enables faster development, scalability, and promotes innovation, allowing organizations to bring new features to market more quickly.','references':'What are Microservices? | AWS. (n.d.). Amazon Web Services, Inc. Retrieved July 30, 2023, from https://aws.amazon.com/microservices/'},
    {'id': 5, 'terms':'Waterfall Model','description':'The Waterfall method is a linear and traditional software development model where each phase is completed before moving on to the next one. It follows a sequential approach, starting with requirement gathering, followed by analysis, design, coding, testing, and deployment, with each phase distinct and predefined from the outset.','references':'Agile VS Waterfall vs DevOps vs Lean -Professional-Devops.com. (n.d.). Retrieved July 30, 2023, from https://www.professional-devops.com/waterfall-agile-devops-lean-devops-lean.html'},
    {'id': 6, 'terms':'Cloud','description':'The cloud encompasses remote servers accessible via the Internet, along with the software and databases hosted on those servers. These cloud servers are distributed across global data centers. Cloud computing allows users and organizations to offload the management of physical servers and software applications, providing convenient and scalable access to computing resources over the Internet.','references':'What is the cloud? | Cloud definition. (n.d.). Cloudflare. Retrieved July 30, 2023, from https://www.cloudflare.com/learning/cloud/what-is-the-cloud/'},
    {'id': 7, 'terms':'express','description':'Express is a web application framework for Node.js, offering a wide range of features to develop web and mobile applications. It facilitates the creation of various types of applications, including single-page, multipage, and hybrid web applications. As a layer built on top of Node.js, Express simplifies server management and routing, making it an efficient choice for web application development.','references':'Express JS Tutorial: What is Express in Node JS? (n.d.). Simplilearn.Com. Retrieved July 30, 2023, from https://www.simplilearn.com/tutorials/nodejs-tutorial/what-is-express-js'},
    {'id': 8, 'terms':'UX','description':'User Experience (UX) design is the process of crafting products that deliver meaningful and relevant experiences to users. It encompasses various aspects, including branding, design, usability, and functionality, throughout the entire process of acquiring and integrating the product. While usability and User Interface (UI) design are vital components of UX, they represent only subsets of the broader user experience design approach.','references':'What is User Experience (UX) Design? (2023, July 31). The Interaction Design Foundation. https://www.interaction-design.org/literature/topics/ux-design'},
    {'id': 9, 'terms':'Bootstrapping','description':'Using Bootstrap, a widely used HTML, CSS, and JavaScript framework, is referred to as bootstrapping when creating responsive and mobile-friendly websites. It offers design templates for a variety of features, including typography, forms, buttons, navigation, and more, and is freely available for download and use. This speeds up and simplifies the web creation process. Bootstrap is a popular option for simpler and quicker web development since it gives developers the tools to construct responsive designs with the inclusion of JavaScript plug-ins.','references':'Kumar, R. (2022, December 14). What is Bootstrap & How it works? An Overview and Its Use Cases!!! DevOpsSchool.Com. https://www.devopsschool.com/blog/what-is-bootstrap-how-it-works-an-overview-and-its-use-case/'},
    {'id': 10, 'terms':'"Shift Left" testing','description':'Software testing techniques known as "shift-left testing" entail bringing the testing process forwards in the software development lifecycle. Shift-left testing incorporates testing operations directly from the start of the development process, as opposed to waiting until the end of the development cycle. This proactive strategy aids in early issue and defect detection and remediation, lowering the cost and labour of correcting issues later in the development cycle and eventually producing software products of higher quality.','references':'Vaddadi, Srinivas & Thatikonda, Ramya & Padthe, Adithya & Arnepalli, Pandu Rangarao. (2023). Shift-Left Testing Paradigm Process Implementation for Quality of Software Based on Fuzzy. 10.21203/rs.3.rs-2845536/v1'}
];

router.get('/', function(req, res, next) {
    res.render('index', {title: 'SIT722 DevOps Glossary', sub:'Welcome to my website showing a collection of DevOps terms and their brief descriptions.', names:itemList});
});

module.exports = router;
